services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node

    container_name: tfm-backend

    working_dir: /app

    ports:
      - "3000:3000"

    volumes:
      - ./backend/node:/app
      - node-modules:/app/node_modules
      - ./web:/web

    environment:
      PORT: 3000

    depends_on:
      - python-api

    restart: unless-stopped

  python-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.python

    container_name: tfm-python-api

    working_dir: /app

    command: uvicorn semantic_search_api:app --reload --host 0.0.0.0 --port 8000

    ports:
      - "8000:8000"

    volumes:
      - ./backend/python:/app
      - ./backend/data:/app/data
      - hf-cache:/root/.cache/huggingface

    restart: unless-stopped

volumes:
  node-modules:
  hf-cache:
