FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV HF_HOME=/root/.cache/huggingface

# Dependencias Python
COPY python/requirements/ ./requirements/

RUN pip install --no-cache-dir -r requirements/requirements-base.txt

RUN pip install --no-cache-dir -r requirements/requirements-pytorch.txt

RUN pip install --no-cache-dir -r requirements/requirements-ai.txt

# Código Python
COPY python/ .

# Base de conocimiento
COPY data ./data

EXPOSE 8000

CMD ["uvicorn", "semantic_search_api:app", "--host", "0.0.0.0", "--port", "8000"]